name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
        type: choice
        options:
          - stable
          - beta
          - alpha
          - patch
          - minor
          - major
          - rc
        default: 'stable'

jobs:
  test:
    runs-on: ubuntu-22.04
    name: Run Cargo Check before building
    steps:
      - name: checkout code
        uses: actions/checkout@v6

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Check Kumo
        run: cargo check
  update-version:
    name: Update Version
    runs-on: ubuntu-22.04
    needs: test
    permissions:
      contents: write
    outputs:
      new_tag: ${{ steps.get-version.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Update version
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          VERSION_TYPE=${{ github.event.inputs.version }}
          
          if [ "$VERSION_TYPE" = "stable" ]; then
            BUMP_TYPE="patch"
          elif [ "$VERSION_TYPE" = "beta" ]; then
            BUMP_TYPE="beta"
          elif [ "$VERSION_TYPE" = "alpha" ]; then
            BUMP_TYPE="alpha"
          elif [ "$VERSION_TYPE" = "minor" ]; then
            BUMP_TYPE="minor"
          elif [ "$VERSION_TYPE" = "major" ]; then
            BUMP_TYPE="major"
          elif [ "$VERSION_TYPE" = "rc" ]; then
            BUMP_TYPE="rc"
          fi
          
          node scripts/bump.js "$BUMP_TYPE"

      - name: Get new version
        id: get-version
        run: |
          NEW_VERSION=$(grep -m 1 '^version = ' crates/cli/Cargo.toml | cut -d '"' -f 2)
          echo "version=v$NEW_VERSION" >> $GITHUB_OUTPUT
  
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: update-version
    strategy:
      matrix:
        os: [
          windows-2022, 
          ubuntu-22.04, 
          macos-14
        ]
        include:
          - os: windows-2022
            artifact_name: kumo-windows.zip
            asset_name: kumo.exe
            kx_name: kx.exe
          - os: ubuntu-22.04
            artifact_name: kumo-linux.tar.gz
            asset_name: kumo
            kx_name: kx
          - os: macos-14
            artifact_name: kumo-macos.tar.gz
            asset_name: kumo
            kx_name: kx

    steps:
    - uses: actions/checkout@v6
      with:
        ref: ${{ needs.update-version.outputs.new_tag }}

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Rust Cache
      uses: Swatinem/rust-cache@v2

    - name: Build Kumo
      run: cargo build --release
      env:
        CARGO_INCREMENTAL: 0
        CARGO_TERM_COLOR: always

    - name: Prepare Artifacts (Windows)
      if: matrix.os == 'windows-2022'
      run: |
        mkdir bin
        cp target/release/kumo.exe bin/
        cp target/release/kx.exe bin/
        7z a ${{ matrix.artifact_name }} ./bin/*

    - name: Prepare Artifacts (Unix)
      if: matrix.os != 'windows-2022'
      run: |
        mkdir bin
        cp target/release/kumo bin/
        cp target/release/kx bin/
        tar -czf ${{ matrix.artifact_name }} -C bin .

    - name: Upload Artifact
      uses: actions/upload-artifact@v7
      with:
        name: ${{ matrix.os }}-build
        path: ${{ matrix.artifact_name }}

  release:
    name: Create GitHub Release
    needs: [build, update-version, test]
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v8

      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ needs.update-version.outputs.new_tag }}
          files: |
            windows-2022-build/kumo-windows.zip
            ubuntu-22.04-build/kumo-linux.tar.gz
            macos-14-build/kumo-macos.tar.gz
          generate_release_notes: true
          prerelease: ${{ contains(needs.update-version.outputs.new_tag, '-') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
